resources:
  containers:
  - container: nginx
    type: ACR  
    azureSubscription: MY-Azure-connection
    resourceGroup: test-trigger
    registry: acrtriggertest1
    repository: nginx
    trigger:
      enabled: true
pool:
  vmImage: 'nginx'
steps:
- bash: echo "Hello world"
      
