apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  namespace: myapp-ns
  labels:
    app: sampleapp
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      serviceAccountName: cicd
      containers:
      - name: sampleapp
        #replace <foobar> with your container registry. Example: contosodemo.azurecr.io
        image: msyinjiecontainerregistry.azurecr.io/project:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        - containerPort: 8080
