apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: myapp-ns
  labels:
    app: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer

--- 
apiVersion: v1
kind: ServiceAccount
metadata:
   name: cicd
   namespace: myapp-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-for-serviceaccount
  namespace: myapp-ns
rules:
- apiGroups: ["*","apps","extensions"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-serviceaccount
  namespace: myapp-ns
subjects:
- kind: ServiceAccount
  name: cicd
  namespace: myapp-ns
roleRef:
  kind: Role
  name: role-for-serviceaccount
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: sa1-token
  namespace: myapp-ns
  annotations:
    kubernetes.io/service-account.name: cicd
type: kubernetes.io/service-account-token